// sidebar
export const SET_SIDEBAR_PAGE_LOCK = 'SET_PAGE_LOCK';
export const SET_SIDEBAR_FILTER = 'SET_SIDEBAR_FILTER';
export const SEARCH_SIDEBAR_MAINBOARD = 'SEARCH_SIDEBAR_MAINBOARD';
export const SET_SIDEBAR_MAINBOARD = 'SET_SIDEBAR_MAINBOARD';
export const USERS_FETCH_DATA_SUCCESS = 'USERS_FETCH_DATA_SUCCESS';
export const USERS_IS_LOADING = 'USERS_IS_LOADING';
export const USERS_HAS_ERRORED = 'USERS_HAS_ERRORED';

// navbar
export const SET_NAVBAR_THEME_CHANGER = 'SET_NAVBAR_THEME_CHANGER';
export const NOTIFICATIONS_FETCH_DATA_SUCCESS = 'NOTIFICATIONS_FETCH_DATA_SUCCESS';
export const NEWS_FETCH_DATA_SUCCESS = 'NEWS_FETCH_DATA_SUCCESS';

// mainpage
export const GALLERY_FETCH_DATA_SUCCESS = 'GALLERY_FETCH_DATA_SUCCESS';

// global page
export const PAGE_FETCH_DATA_SUCCESS = 'PAGE_FETCH_DATA_SUCCESS';
export const PAGE_IS_LOADING = 'PAGE_IS_LOADING';
export const PAGE_HAS_ERRORED = 'PAGE_HAS_ERRORED';

// global misc
export const SET_MODAL_THEME_CHANGER = 'SET_MODAL_THEME_CHANGER';