export const SET_SIDEBAR_FILTER = 'SET_SIDEBAR_FILTER';
export const SEARCH_SIDEBAR_MAINBOARD = 'SEARCH_SIDEBAR_MAINBOARD';
export const SET_SIDEBAR_MAINBOARD = 'SET_SIDEBAR_MAINBOARD';
export const USERS_FETCH_DATA_SUCCESS = 'USERS_FETCH_DATA_SUCCESS';
export const USERS_IS_LOADING = 'USERS_IS_LOADING';
export const USERS_HAS_ERRORED = 'USERS_HAS_ERRORED';

export const PAGE_FETCH_DATA_SUCCESS = 'PAGE_FETCH_DATA_SUCCESS';
export const PAGE_IS_LOADING = 'PAGE_IS_LOADING';
export const PAGE_HAS_ERRORED = 'PAGE_HAS_ERRORED';